site_name: MAX78000 User Guide
site_url: https://kayaoglutuncay.github.io/max78000/
docs_dir: src
site_dir: docs
nav:
  - Home: index.md
  - Memory, Register, Mapping: memory-register-mapping-access.md
  - System, Power, Clocks, Reset: system-power-clocks-reset.md
  - Flash Controller: flash-controller.md
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  font:
    text: Merriweather Sans
    code: Red Hat Mono
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - css/extra.css
plugins:
  - search
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js