name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install mkdocs-material and all its dependencies
          pip install \
            mkdocs-material \
            mkdocs-material-extensions \
            python-markdown-math \
            mkdocs-minify-plugin \
            mkdocs-redirects \
            pygments
          
      - name: Show installed packages
        run: pip freeze
          
      - name: Build site
        run: |
          mkdocs build --verbose
          
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          git checkout gh-pages || git checkout -b gh-pages
          git rm -rf .
          git clean -fdx
          cp -r site/* .
          rm -rf site
          
          # Debug: List files to verify content
          echo "Files to be deployed:"
          ls -la
          
          git add .
          git commit -m "Deploy documentation updates"
          git push origin gh-pages --force